server:
  port: 1123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yaples
    db-type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

