server:
  port: 1123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yaples?useSSL=false&autoReconnect=true&characterEncoding=utf8
    db-type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
    initial-size: 20
    max-idle: 60
    max-wait: 10000
    min-idle: 10
    max-active: 200
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

